version: '3.2'

services:
  keylla-frontend:
    build: frontend
    container_name: keylla-frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - keylla-network
    depends_on:
      - keylla-mysql

  keylla-backend:
    build: backend
    container_name: keylla-backend
    ports:
      - 20081:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - keylla-network
    depends_on:
      - keylla-mysql

  keylla-mysql:
    image: mysql
    container_name: keylla-mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=acupuncture
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=acupuncture
      - MYSQL_DATABASE=acupuncture
    networks:
      - keylla-network
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/data:/var/lib/mysql

  keylla-phpmyqdmin:
    image: phpmyadmin/phpmyadmin
    container_name: keylla-phpmyqdmin
    ports:
      - "20082:80"
    networks:
      - keylla-network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=keylla-mysql
    depends_on:
      - keylla-mysql

networks:
  keylla-network:
    driver: bridge
